### ISSUE TITLE
Add support for block storage

### ISSUE THREAD

**Issue by bryanl** [fog/fog-digitalocean#5]
I'm adding this issue as a reminder. There is a branch with this work in there, but it isn't ready to go yet.

**Comment by h0lyalg0rithm** [comment]
Thanks for the reminder,I am planning to port the rest of the PRs from fog/fog to this repo

**Comment by bryanl** [comment]
It was a reminder for myself, I have lots of api clients to support :)

**Comment by sam0x17** [comment]
👍
